In [49]:
# 1. Define the full path (already done correctly!)
file_path = r'C:\Users\Himaja\OneDrive\Documents\himaja\AI\names.txt'

# 2. Use the variable 'file_path' instead of the string 'names.txt'
words = open(file_path, 'r').read().splitlines()

In [50]:
words[:9]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper']

In [51]:
len(words)

32033

In [52]:
min(len(w) for w in words)

2

In [53]:
max(len(w) for w in words)

15

In [54]:
#bigram lan model
#2 cahr at a time
b={}
for w in words:
    chs=['<S>'] + list(w) +['<E>']
    for ch1,ch2 in zip(chs,chs[1:]):
        bigram=(ch1,ch2)
        b[bigram]=b.get(bigram,0)+1
        #print(ch1,ch2)
    


In [55]:
sorted(b.items(),key=lambda kv:-kv[1])#kwyvalue kv


[(('n', '<E>'), 6763),
 (('a', '<E>'), 6640),
 (('a', 'n'), 5438),
 (('<S>', 'a'), 4410),
 (('e', '<E>'), 3983),
 (('a', 'r'), 3264),
 (('e', 'l'), 3248),
 (('r', 'i'), 3033),
 (('n', 'a'), 2977),
 (('<S>', 'k'), 2963),
 (('l', 'e'), 2921),
 (('e', 'n'), 2675),
 (('l', 'a'), 2623),
 (('m', 'a'), 2590),
 (('<S>', 'm'), 2538),
 (('a', 'l'), 2528),
 (('i', '<E>'), 2489),
 (('l', 'i'), 2480),
 (('i', 'a'), 2445),
 (('<S>', 'j'), 2422),
 (('o', 'n'), 2411),
 (('h', '<E>'), 2409),
 (('r', 'a'), 2356),
 (('a', 'h'), 2332),
 (('h', 'a'), 2244),
 (('y', 'a'), 2143),
 (('i', 'n'), 2126),
 (('<S>', 's'), 2055),
 (('a', 'y'), 2050),
 (('y', '<E>'), 2007),
 (('e', 'r'), 1958),
 (('n', 'n'), 1906),
 (('y', 'n'), 1826),
 (('k', 'a'), 1731),
 (('n', 'i'), 1725),
 (('r', 'e'), 1697),
 (('<S>', 'd'), 1690),
 (('i', 'e'), 1653),
 (('a', 'i'), 1650),
 (('<S>', 'r'), 1639),
 (('a', 'm'), 1634),
 (('l', 'y'), 1588),
 (('<S>', 'l'), 1572),
 (('<S>', 'c'), 1542),
 (('<S>', 'e'), 1531),
 (('j', 'a'), 1473),
 (

In [56]:
#rows are ch1 col ch2 2d array useing py torch 
import torch

In [57]:
N=torch.zeros((27,27),dtype=torch.int32)#tensors

#for indexes we need a lookup table

In [58]:
chars=sorted(list(set(''.join(words))))
#we use set as list because they dont have the duplicates
stoi={s:i+1 for i,s in enumerate(chars)}#string to indes\xting mapping
stoi['.']=0
itos={i:s for s,i in stoi.items()}

In [59]:
for w in words:
    chs = ['.'] + list(w) + ['.']  
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1, ix2] += 1


In [60]:
N

tensor([[   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
         1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
          134,  535,  929],
        [6640,  556,  541,  470, 1042,  692,  134,  168, 2332, 1650,  175,  568,
         2528, 1634, 5438,   63,   82,   60, 3264, 1118,  687,  381,  834,  161,
          182, 2050,  435],
        [ 114,  321,   38,    1,   65,  655,    0,    0,   41,  217,    1,    0,
          103,    0,    4,  105,    0,    0,  842,    8,    2,   45,    0,    0,
            0,   83,    0],
        [  97,  815,    0,   42,    1,  551,    0,    2,  664,  271,    3,  316,
          116,    0,    0,  380,    1,   11,   76,    5,   35,   35,    0,    0,
            3,  104,    4],
        [ 516, 1303,    1,    3,  149, 1283,    5,   25,  118,  674,    9,    3,
           60,   30,   31,  378,    0,    1,  424,   29,    4,   92,   17,   23,
            0,  317,    1],
        [3983,  679,  121,  153,  384, 1271,   82,

In [61]:
import matplotlib.pyplot as plt
%matplotlib inline
'''plt.figure(figsize=(16,16))
#plt.imshow(N,cmap="Blues")
for i in range(27):
    for j in range(27):
        chstr=itos[i]+itos[j]
        plt.text(j,i,chstr,ha="center",va="bottom",color="gray")
        plt.text(j,i,N[i,j].item(),ha="center",va="bottom",color="gray")'''


'plt.figure(figsize=(16,16))\n#plt.imshow(N,cmap="Blues")\nfor i in range(27):\n    for j in range(27):\n        chstr=itos[i]+itos[j]\n        plt.text(j,i,chstr,ha="center",va="bottom",color="gray")\n        plt.text(j,i,N[i,j].item(),ha="center",va="bottom",color="gray")'

In [62]:
N[0]

tensor([   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
        1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
         134,  535,  929], dtype=torch.int32)

In [63]:
p=N[0].float()#normalising thats why float
p=p/p.sum()
p

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])

In [64]:
#torch.multinomial used for probality ad for sampilisation
#uses genretor in pytorch

g = torch.Generator().manual_seed(2147483647)
ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
itos[ix]

'c'

In [65]:
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3, generator=g)
p = p / p.sum()
p

tensor([0.6064, 0.3033, 0.0903])

In [66]:
torch.multinomial(p, num_samples=100, replacement=True, generator=g)

tensor([1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
        0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0,
        0, 1, 1, 1])

In [67]:
p.shape

torch.Size([3])

In [68]:
P=(N+1).float()
P/= P.sum(1,keepdims=True)

In [69]:
g = torch.Generator().manual_seed(2147483647)

for i in range(5):
  
  out = []
  ix = 0
  while True:
    p = P[ix]
    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    out.append(itos[ix])
    if ix == 0:
      break
  print(''.join(out))

cexze.
momasurailezitynn.
konimittain.
llayn.
ka.


In [70]:
log_likelihood = 0.0
n = 0

for w in words:
#for w in ["andrejq"]:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2 in zip(chs, chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    prob = P[ix1, ix2]
    logprob = torch.log(prob)
    log_likelihood += logprob
    n += 1
    #print(f'{ch1}{ch2}: {prob:.4f} {logprob:.4f}')

print(f'{log_likelihood=}')
nll = -log_likelihood
print(f'{nll=}')
print(f'{nll/n}')

log_likelihood=tensor(-559951.5625)
nll=tensor(559951.5625)
2.4543561935424805


In [71]:
#creating dataset trainfing for bigrmas

In [72]:
# Change this:


# To this:
xs, ys = [], [] 

for w in words[:1]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        print(ch1, ch2)
        xs.append(ix1)
        ys.append(ix2)

xs = torch.tensor(xs)
ys = torch.tensor(ys)

. e
e m
m m
m a
a .


In [73]:
xs


tensor([ 0,  5, 13, 13,  1])

In [74]:
ys


tensor([ 5, 13, 13,  1,  0])

In [75]:
import torch.nn.functional as F
xenc=F.one_hot(xs,num_classes=27).float()#neurals feed float not int
xenc


tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [76]:
#plt.imshow(xenc)

In [77]:
 #1 neuron
W= torch.randn(27,27)#wea re getting prob fo rnext char
xenc@W

tensor([[-0.5168, -0.9695, -0.3805, -0.3905, -0.7278, -0.0374,  0.1740,  1.7737,
         -0.7066, -1.5386,  1.3507, -1.1558,  0.3893, -0.3722, -0.0465,  0.3465,
         -0.0744, -0.2934,  1.5235, -1.5717, -0.7168,  1.4848,  1.3885, -0.2500,
          0.4087,  1.9775, -1.4423],
        [ 0.5946,  0.3617, -0.6970, -0.3789, -0.3391,  0.2819, -1.8462,  0.8481,
          0.6219, -0.3773, -0.0895,  1.5491,  0.0098, -2.3499,  1.7865,  1.4150,
         -0.1500, -0.9447,  0.5440, -0.5880,  0.6194,  0.0135,  0.7124,  1.0264,
         -1.6609, -0.9140, -0.1153],
        [-0.4638, -0.1521, -1.0771,  1.6639,  0.9707,  1.7057,  0.8808, -1.2119,
         -2.6141,  0.3997, -1.6956,  1.5639,  0.8058,  0.4043, -0.0649,  1.2454,
          0.5872, -0.5673, -1.3541, -0.1609, -0.3115,  3.0268, -0.8054, -0.0424,
          1.1128, -0.1793,  1.2573],
        [-0.4638, -0.1521, -1.0771,  1.6639,  0.9707,  1.7057,  0.8808, -1.2119,
         -2.6141,  0.3997, -1.6956,  1.5639,  0.8058,  0.4043, -0.0649,  1.2454

In [78]:
logits=(xenc@W)
counts=logits.exp()
probs=counts/counts.sum(1,keepdims=True)
probs
#used to entrpret like counts

tensor([[0.0131, 0.0084, 0.0151, 0.0149, 0.0106, 0.0212, 0.0262, 0.1298, 0.0109,
         0.0047, 0.0850, 0.0069, 0.0325, 0.0152, 0.0210, 0.0311, 0.0204, 0.0164,
         0.1010, 0.0046, 0.0108, 0.0972, 0.0883, 0.0172, 0.0331, 0.1591, 0.0052],
        [0.0442, 0.0350, 0.0121, 0.0167, 0.0174, 0.0323, 0.0038, 0.0569, 0.0454,
         0.0167, 0.0223, 0.1147, 0.0246, 0.0023, 0.1455, 0.1003, 0.0210, 0.0095,
         0.0420, 0.0135, 0.0453, 0.0247, 0.0497, 0.0680, 0.0046, 0.0098, 0.0217],
        [0.0095, 0.0130, 0.0051, 0.0797, 0.0398, 0.0831, 0.0364, 0.0045, 0.0011,
         0.0225, 0.0028, 0.0721, 0.0338, 0.0226, 0.0141, 0.0524, 0.0271, 0.0086,
         0.0039, 0.0128, 0.0110, 0.3113, 0.0067, 0.0145, 0.0459, 0.0126, 0.0530],
        [0.0095, 0.0130, 0.0051, 0.0797, 0.0398, 0.0831, 0.0364, 0.0045, 0.0011,
         0.0225, 0.0028, 0.0721, 0.0338, 0.0226, 0.0141, 0.0524, 0.0271, 0.0086,
         0.0039, 0.0128, 0.0110, 0.3113, 0.0067, 0.0145, 0.0459, 0.0126, 0.0530],
        [0.0031, 0.0401,

In [79]:
probs[0].sum()

tensor(1.)

In [80]:
xs

tensor([ 0,  5, 13, 13,  1])

In [81]:
ys

tensor([ 5, 13, 13,  1,  0])

In [82]:
g=torch.Generator().manual_seed(2147483647+1)
W=torch.randn((27,27),generator=g)

In [83]:
xenc = F.one_hot(xs, num_classes=27).float() # input to the network: one-hot encoding
logits = xenc @ W # predict log-counts
counts = logits.exp() # counts, equivalent to N
probs = counts / counts.sum(1, keepdims=True)#softmax

In [84]:
probs.shape

torch.Size([5, 27])

In [85]:
nlls = torch.zeros(5)
for i in range(5):
  # i-th bigram:
  x = xs[i].item() # input character index
  y = ys[i].item() # label character index
  print('--------')
  print(f'bigram example {i+1}: {itos[x]}{itos[y]} (indexes {x},{y})')
  print('input to the neural net:', x)
  print('output probabilities from the neural net:', probs[i])
  print('label (actual next character):', y)
  p = probs[i, y]
  print('probability assigned by the net to the the correct character:', p.item())
  logp = torch.log(p)
  print('log likelihood:', logp.item())
  nll = -logp
  print('negative log likelihood:', nll.item())
  nlls[i] = nll

print('=========')
print('average negative log likelihood, i.e. loss =', nlls.mean().item())

--------
bigram example 1: .e (indexes 0,5)
input to the neural net: 0
output probabilities from the neural net: tensor([0.0049, 0.0959, 0.0281, 0.0703, 0.0961, 0.0573, 0.0241, 0.0135, 0.0093,
        0.1416, 0.0225, 0.0217, 0.0513, 0.0106, 0.0097, 0.0291, 0.0229, 0.0273,
        0.0325, 0.0275, 0.0446, 0.0501, 0.0214, 0.0093, 0.0120, 0.0354, 0.0310])
label (actual next character): 5
probability assigned by the net to the the correct character: 0.05734505504369736
log likelihood: -2.858668565750122
negative log likelihood: 2.858668565750122
--------
bigram example 2: em (indexes 5,13)
input to the neural net: 5
output probabilities from the neural net: tensor([0.0426, 0.0113, 0.0266, 0.0507, 0.2370, 0.0580, 0.0421, 0.0094, 0.0136,
        0.0297, 0.0044, 0.0782, 0.1028, 0.0146, 0.0172, 0.0288, 0.0263, 0.0319,
        0.0248, 0.0210, 0.0063, 0.0057, 0.0309, 0.0269, 0.0298, 0.0089, 0.0205])
label (actual next character): 13
probability assigned by the net to the the correct character: 0.

In [86]:
#optimiser
#minimisie loss my tuning W with gradient basedd


In [90]:
xs, ys = [], []
for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2 in zip(chs, chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    xs.append(ix1)
    ys.append(ix2)
xs = torch.tensor(xs)
ys = torch.tensor(ys)
num = xs.nelement()
print('number of examples: ', num)

# initialize the 'network'
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27, 27), generator=g, requires_grad=True)


number of examples:  228146


In [88]:
# gradient descent
for k in range(100):
  
  # forward pass
  xenc = F.one_hot(xs, num_classes=27).float() # input to the network: one-hot encoding
  logits = xenc @ W # predict log-counts
  counts = logits.exp() # counts, equivalent to N
  probs = counts / counts.sum(1, keepdims=True) # probabilities for next character
  loss = -probs[torch.arange(num), ys].log().mean() + 0.01*(W**2).mean()
  print(loss.item())
  
  # backward pass
  W.grad = None # set to zero the gradient
  loss.backward()
  
  # update
  W.data += -50 * W.grad

3.7686190605163574
3.3788068294525146
3.161090850830078
3.027186155319214
2.9344842433929443
2.8672313690185547
2.816654682159424
2.777146577835083
2.745253801345825
2.7188303470611572
2.696505546569824
2.6773719787597656
2.6608052253723145
2.6463515758514404
2.633665084838867
2.622471570968628
2.6125476360321045
2.6037068367004395
2.595794916152954
2.5886809825897217
2.582256317138672
2.5764293670654297
2.5711238384246826
2.566272735595703
2.5618226528167725
2.5577263832092285
2.5539445877075195
2.550442695617676
2.547192335128784
2.5441696643829346
2.5413525104522705
2.538722038269043
2.536262035369873
2.5339581966400146
2.531797409057617
2.5297679901123047
2.527860164642334
2.5260636806488037
2.5243709087371826
2.522773265838623
2.521263837814331
2.519836664199829
2.5184857845306396
2.5172057151794434
2.515990734100342
2.5148372650146484
2.5137410163879395
2.512697696685791
2.511704444885254
2.5107581615448
2.509855031967163
2.5089924335479736
2.5081686973571777
2.507380485534668
2.

In [89]:
g = torch.Generator().manual_seed(2147483647)

for i in range(10):
  
  out = []
  ix = 0
  while True:
    
    # ----------
    # BEFORE:
    #p = P[ix]
    # ----------
    # NOW:
    xenc = F.one_hot(torch.tensor([ix]), num_classes=27).float()
    logits = xenc @ W # predict log-counts
    counts = logits.exp() # counts, equivalent to N
    p = counts / counts.sum(1, keepdims=True) # probabilities for next character
    # ----------
    
    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    out.append(itos[ix])
    if ix == 0:
      break
  print(''.join(out))

cexze.
momasurailezityha.
konimittain.
llayn.
ka.
da.
staiyaubrtthrigotai.
moliellavo.
ke.
teda.
