In [1]:
# 1. Define the full path (already done correctly!)
file_path = r'C:\Users\Himaja\OneDrive\Documents\himaja\AI\names.txt'

# 2. Use the variable 'file_path' instead of the string 'names.txt'
words = open(file_path, 'r').read().splitlines()

In [2]:
words[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [3]:
len(words)

32033

In [4]:
min(len(w) for w in words)

2

In [5]:
max(len(w) for w in words)

15

In [6]:
#bigram lan model
#2 cahr at a time
b={}
for w in words:
    chs=['<S>'] + list(w) +['<E>']
    for ch1,ch2 in zip(chs,chs[1:]):
        bigram=(ch1,ch2)
        b[bigram]=b.get(bigram,0)+1
        #print(ch1,ch2)
    


In [7]:
sorted(b.items(),key=lambda kv:-kv[1])#kwyvalue kv


[(('n', '<E>'), 6763),
 (('a', '<E>'), 6640),
 (('a', 'n'), 5438),
 (('<S>', 'a'), 4410),
 (('e', '<E>'), 3983),
 (('a', 'r'), 3264),
 (('e', 'l'), 3248),
 (('r', 'i'), 3033),
 (('n', 'a'), 2977),
 (('<S>', 'k'), 2963),
 (('l', 'e'), 2921),
 (('e', 'n'), 2675),
 (('l', 'a'), 2623),
 (('m', 'a'), 2590),
 (('<S>', 'm'), 2538),
 (('a', 'l'), 2528),
 (('i', '<E>'), 2489),
 (('l', 'i'), 2480),
 (('i', 'a'), 2445),
 (('<S>', 'j'), 2422),
 (('o', 'n'), 2411),
 (('h', '<E>'), 2409),
 (('r', 'a'), 2356),
 (('a', 'h'), 2332),
 (('h', 'a'), 2244),
 (('y', 'a'), 2143),
 (('i', 'n'), 2126),
 (('<S>', 's'), 2055),
 (('a', 'y'), 2050),
 (('y', '<E>'), 2007),
 (('e', 'r'), 1958),
 (('n', 'n'), 1906),
 (('y', 'n'), 1826),
 (('k', 'a'), 1731),
 (('n', 'i'), 1725),
 (('r', 'e'), 1697),
 (('<S>', 'd'), 1690),
 (('i', 'e'), 1653),
 (('a', 'i'), 1650),
 (('<S>', 'r'), 1639),
 (('a', 'm'), 1634),
 (('l', 'y'), 1588),
 (('<S>', 'l'), 1572),
 (('<S>', 'c'), 1542),
 (('<S>', 'e'), 1531),
 (('j', 'a'), 1473),
 (

In [8]:
#rows are ch1 col ch2 2d array useing py torch 
import torch

In [9]:
N=torch.zeros((27,27),dtype=torch.int32)#tensors

#for indexes we need a lookup table

In [10]:
chars=sorted(list(set(''.join(words))))
#we use set as list because they dont have the duplicates
stoi={s:i+1 for i,s in enumerate(chars)}#string to indes\xting mapping
stoi['.']=0
itos={i:s for s,i in stoi.items()}

In [11]:
for w in words:
    chs = ['.'] + list(w) + ['.']  
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1, ix2] += 1


In [12]:
N

tensor([[   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
         1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
          134,  535,  929],
        [6640,  556,  541,  470, 1042,  692,  134,  168, 2332, 1650,  175,  568,
         2528, 1634, 5438,   63,   82,   60, 3264, 1118,  687,  381,  834,  161,
          182, 2050,  435],
        [ 114,  321,   38,    1,   65,  655,    0,    0,   41,  217,    1,    0,
          103,    0,    4,  105,    0,    0,  842,    8,    2,   45,    0,    0,
            0,   83,    0],
        [  97,  815,    0,   42,    1,  551,    0,    2,  664,  271,    3,  316,
          116,    0,    0,  380,    1,   11,   76,    5,   35,   35,    0,    0,
            3,  104,    4],
        [ 516, 1303,    1,    3,  149, 1283,    5,   25,  118,  674,    9,    3,
           60,   30,   31,  378,    0,    1,  424,   29,    4,   92,   17,   23,
            0,  317,    1],
        [3983,  679,  121,  153,  384, 1271,   82,

In [13]:
import matplotlib.pyplot as plt
%matplotlib inline
'''plt.figure(figsize=(16,16))
#plt.imshow(N,cmap="Blues")
for i in range(27):
    for j in range(27):
        chstr=itos[i]+itos[j]
        plt.text(j,i,chstr,ha="center",va="bottom",color="gray")
        plt.text(j,i,N[i,j].item(),ha="center",va="bottom",color="gray")'''


'plt.figure(figsize=(16,16))\n#plt.imshow(N,cmap="Blues")\nfor i in range(27):\n    for j in range(27):\n        chstr=itos[i]+itos[j]\n        plt.text(j,i,chstr,ha="center",va="bottom",color="gray")\n        plt.text(j,i,N[i,j].item(),ha="center",va="bottom",color="gray")'

In [14]:
N[0]

tensor([   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
        1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
         134,  535,  929], dtype=torch.int32)

In [15]:
p=N[0].float()#normalising thats why float
p=p/p.sum()
p

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])

In [16]:
#torch.multinomial used for probality ad for sampilisation
#uses genretor in pytorch

g = torch.Generator().manual_seed(2147483647)
ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
itos[ix]

'c'

In [17]:
g = torch.Generator().manual_seed(2147483647)
p = torch.rand(3, generator=g)
p = p / p.sum()
p

tensor([0.6064, 0.3033, 0.0903])

In [18]:
torch.multinomial(p, num_samples=100, replacement=True, generator=g)

tensor([1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
        0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0,
        0, 1, 1, 1])

In [19]:
p.shape

torch.Size([3])

In [20]:
P=(N+1).float()
P/= P.sum(1,keepdims=True)

In [21]:
g = torch.Generator().manual_seed(2147483647)

for i in range(5):
  
  out = []
  ix = 0
  while True:
    p = P[ix]
    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    out.append(itos[ix])
    if ix == 0:
      break
  print(''.join(out))

cexze.
momasurailezitynn.
konimittain.
llayn.
ka.


In [22]:
log_likelihood = 0.0
n = 0

for w in words:
#for w in ["andrejq"]:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2 in zip(chs, chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    prob = P[ix1, ix2]
    logprob = torch.log(prob)
    log_likelihood += logprob
    n += 1
    #print(f'{ch1}{ch2}: {prob:.4f} {logprob:.4f}')

print(f'{log_likelihood=}')
nll = -log_likelihood
print(f'{nll=}')
print(f'{nll/n}')

log_likelihood=tensor(-559951.5625)
nll=tensor(559951.5625)
2.4543561935424805


In [23]:
#creating dataset trainfing for bigrmas

In [27]:
# Change this:


# To this:
xs, ys = [], [] 

for w in words[:1]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        print(ch1, ch2)
        xs.append(ix1)
        ys.append(ix2)

xs = torch.tensor(xs)
ys = torch.tensor(ys)

. e
e m
m m
m a
a .


In [29]:
xs


tensor([ 0,  5, 13, 13,  1])

In [31]:
ys


tensor([ 5, 13, 13,  1,  0])

In [33]:
import torch.nn.functional as F
xenc=F.one_hot(xs,num_classes=27).float()#neurals feed float not int
xenc


tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#plt.imshow(xenc)

In [45]:
 #1 neuron
W= torch.randn(27,27)#wea re getting prob fo rnext char
xenc@W

tensor([[ 1.2325, -0.6430,  0.5933,  0.3788, -0.2977, -0.1553, -0.3472, -0.0511,
          1.0535, -1.1803, -1.3310, -1.5312,  0.9969, -2.0584, -2.2735,  0.1668,
          1.3940, -0.5316,  0.4073,  0.6097, -3.2573, -1.1229,  0.2957,  0.6205,
         -0.6298,  0.5505,  0.2122],
        [ 0.6237, -1.5754, -1.3698,  0.7311,  1.4984,  1.2688, -1.5583, -1.5369,
          1.1285,  0.7192, -0.9189, -0.1181,  0.1149, -0.0741,  1.7586, -1.6549,
          0.1061,  1.3537,  1.3328,  0.5175, -0.3960,  0.9287, -0.4932,  1.0199,
         -0.1559,  0.3675, -1.0015],
        [-0.3543,  0.4896, -1.1595,  0.0468,  0.4442,  1.3206,  0.4023,  0.2938,
          0.7671, -0.4054,  1.2234, -1.1239, -0.1996,  0.0061, -1.5695,  0.2344,
         -0.6998, -1.4755, -1.4598,  0.8258,  0.5600, -1.2374, -0.1431,  1.0668,
          0.7367, -0.6001,  0.7974],
        [-0.3543,  0.4896, -1.1595,  0.0468,  0.4442,  1.3206,  0.4023,  0.2938,
          0.7671, -0.4054,  1.2234, -1.1239, -0.1996,  0.0061, -1.5695,  0.2344

In [57]:
logits=(xenc@W)
counts=logits.exp()
probs=counts/counts.sum(1,keepdims=True)
probs
#used to entrpret like counts

tensor([[0.1030, 0.0158, 0.0544, 0.0439, 0.0223, 0.0257, 0.0212, 0.0285, 0.0861,
         0.0092, 0.0079, 0.0065, 0.0814, 0.0038, 0.0031, 0.0355, 0.1211, 0.0177,
         0.0451, 0.0553, 0.0012, 0.0098, 0.0404, 0.0559, 0.0160, 0.0521, 0.0371],
        [0.0397, 0.0044, 0.0054, 0.0442, 0.0951, 0.0756, 0.0045, 0.0046, 0.0657,
         0.0436, 0.0085, 0.0189, 0.0238, 0.0197, 0.1234, 0.0041, 0.0236, 0.0823,
         0.0806, 0.0357, 0.0143, 0.0538, 0.0130, 0.0589, 0.0182, 0.0307, 0.0078],
        [0.0197, 0.0458, 0.0088, 0.0294, 0.0438, 0.1052, 0.0420, 0.0377, 0.0605,
         0.0187, 0.0955, 0.0091, 0.0230, 0.0283, 0.0058, 0.0355, 0.0140, 0.0064,
         0.0065, 0.0642, 0.0492, 0.0082, 0.0244, 0.0817, 0.0587, 0.0154, 0.0624],
        [0.0197, 0.0458, 0.0088, 0.0294, 0.0438, 0.1052, 0.0420, 0.0377, 0.0605,
         0.0187, 0.0955, 0.0091, 0.0230, 0.0283, 0.0058, 0.0355, 0.0140, 0.0064,
         0.0065, 0.0642, 0.0492, 0.0082, 0.0244, 0.0817, 0.0587, 0.0154, 0.0624],
        [0.0180, 0.0750,

In [61]:
probs[0].sum()

tensor(1.0000)

In [63]:
xs

tensor([ 0,  5, 13, 13,  1])

In [65]:
ys

tensor([ 5, 13, 13,  1,  0])

In [77]:
g=torch.Generator().manual_seed(2147483647+1)
W=torch.randn((27,27),generator=g)

In [79]:
xenc = F.one_hot(xs, num_classes=27).float() # input to the network: one-hot encoding
logits = xenc @ W # predict log-counts
counts = logits.exp() # counts, equivalent to N
probs = counts / counts.sum(1, keepdims=True)#softmax

In [81]:
probs.shape

torch.Size([5, 27])

In [83]:
nlls = torch.zeros(5)
for i in range(5):
  # i-th bigram:
  x = xs[i].item() # input character index
  y = ys[i].item() # label character index
  print('--------')
  print(f'bigram example {i+1}: {itos[x]}{itos[y]} (indexes {x},{y})')
  print('input to the neural net:', x)
  print('output probabilities from the neural net:', probs[i])
  print('label (actual next character):', y)
  p = probs[i, y]
  print('probability assigned by the net to the the correct character:', p.item())
  logp = torch.log(p)
  print('log likelihood:', logp.item())
  nll = -logp
  print('negative log likelihood:', nll.item())
  nlls[i] = nll

print('=========')
print('average negative log likelihood, i.e. loss =', nlls.mean().item())

--------
bigram example 1: .e (indexes 0,5)
input to the neural net: 0
output probabilities from the neural net: tensor([0.0049, 0.0959, 0.0281, 0.0703, 0.0961, 0.0573, 0.0241, 0.0135, 0.0093,
        0.1416, 0.0225, 0.0217, 0.0513, 0.0106, 0.0097, 0.0291, 0.0229, 0.0273,
        0.0325, 0.0275, 0.0446, 0.0501, 0.0214, 0.0093, 0.0120, 0.0354, 0.0310])
label (actual next character): 5
probability assigned by the net to the the correct character: 0.05734505504369736
log likelihood: -2.858668565750122
negative log likelihood: 2.858668565750122
--------
bigram example 2: em (indexes 5,13)
input to the neural net: 5
output probabilities from the neural net: tensor([0.0426, 0.0113, 0.0266, 0.0507, 0.2370, 0.0580, 0.0421, 0.0094, 0.0136,
        0.0297, 0.0044, 0.0782, 0.1028, 0.0146, 0.0172, 0.0288, 0.0263, 0.0319,
        0.0248, 0.0210, 0.0063, 0.0057, 0.0309, 0.0269, 0.0298, 0.0089, 0.0205])
label (actual next character): 13
probability assigned by the net to the the correct character: 0.

In [ ]:
#optimiser
#minimisie loss my tuning W with gradient basedd
